/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package de.mgrimpo.adventofcode.year2019;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        Day3 classUnderTest = new Day3();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
